install_data('com.silicondust.HDHomeRunConfig.desktop',
  install_dir: get_option('datadir') / 'applications'
)

install_data('com.silicondust.HDHomeRunConfig.metainfo.xml',
  install_dir: get_option('datadir') / 'metainfo'
)

install_data('com.silicondust.HDHomeRunConfig.svg',
  install_dir: get_option('datadir') / 'icons/hicolor/scalable/apps'
)
